version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: sofi
      POSTGRES_USER: tsar
      POSTGRES_PASSWORD: gvidon
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on:
      - db
      
  freegpt-neurogen:
    neurogengpt:
    build: .
    dockerfile: /Users/nemo/vs_code/neuro-gpt/dockerfile
    ports:
      - "7860:7860"
      - "1337:1337"
    env_file:
      - .env
    depends_on:
      - bot     