version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: sofi
      POSTGRES_USER: tsar
      POSTGRES_PASSWORD: gvidon
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  freegpt-neurogen:
    image: freegpt-neurogen
    build:
      context: .
      dockerfile: freeGPT/Dockerfile
    ports:
      - "1338:1338"
      - "1337:1337"
    depends_on:
      - bot     