name: FreeGPT by Neurogen - Versioned Images

on:
#  push:
#    branches:
#      - 'develop'
  schedule:
    #“At 00:00 on Tuesday, Thursday, and Saturday.”
    - cron:  '0 0 * * 2,4,6' 

jobs:

##################################################################################

  build-freegpt-image-versioned:
    name: Build and deploy all versions
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log into registry
      run:  echo "${{ secrets.DOCKER_SERVER_KEY }}" | docker login -u "${{ secrets.DOCKER_SERVER_LOGIN }}" --password-stdin

    - name: Build and Deploy FreeGPT by Neurogen 1.0
      run:  cd .github/docker/1.0 && make build && make deploy

    - name: Build and Deploy FreeGPT by Neurogen 1.1
      run:  cd .github/docker/1.1 && make build && make deploy
      
    - name: Build and Deploy FreeGPT by Neurogen 1.2
      run:  cd .github/docker/1.2 && make build && make deploy
      
    - name: Build and Deploy FreeGPT by Neurogen 1.3
      run:  cd .github/docker/1.3 && make build && make deploy
      
    - name: Build and Deploy FreeGPT by Neurogen 1.3.1
      run:  cd .github/docker/1.3.1 && make build && make deploy
      
    - name: Build and Deploy FreeGPT by Neurogen 1.3.2
      run:  cd .github/docker/1.3.2 && make build && make deploy
      
    - name: Build and Deploy FreeGPT by Neurogen 1.4
      run:  cd .github/docker/1.4 && make build && make deploy
      
##################################################################################
